name: dummy_yaml

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  bdd_widget_test:
    path: ../
  build_runner: null
  flutter_test:
    sdk: flutter
