language: dart
dist: xenial
branches:
  only: [master]
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter pub get
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache