include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    # workaround for https://github.com/dart-lang/sdk/issues/42910
    - 'example/**'

linter:
  rules:
    avoid_positional_boolean_parameters: false
    cascade_invocations: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
