name: bdd_widget_test
description: A BDD-style widget testing library. Generates Flutter widget tests from *.feature files.
version: 0.1.7
author: Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/bdd_widget_test

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.6.1
  build_config: ^0.4.5
  characters: ^1.0.0
  flutter:
    sdk: flutter
  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.11.0
  extra_pedantic: ^1.2.0
  flutter_test:
    sdk: flutter
