name: bdd_widget_test
description: A BDD-style widget testing library. Generates Flutter widget tests from *.feature files.
version: 0.1.4
author: Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/bdd_widget_test

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.3.0
  build_config: ^0.4.2
  strings: ^0.1.2
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
